# Generated by Django 5.1.1 on 2024-10-31 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0003_alter_board_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('coordinates', models.JSONField()),
                ('is_finished', models.BooleanField(default=False)),
                ('checkbox_id', models.CharField(max_length=100)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='board.board')),
            ],
        ),
    ]
